FROM golang:1.23-alpine AS builder

[[- if .IsSQLite]]
RUN apk add --no-cache gcc musl-dev
[[- end]]

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
[[- if .IsSQLite]]
RUN CGO_ENABLED=1 go build -o [[.ProjectName]] .
[[- else]]
RUN CGO_ENABLED=0 go build -o [[.ProjectName]] .
[[- end]]

FROM alpine:3.20
RUN apk add --no-cache ca-certificates tzdata
WORKDIR /app
COPY --from=builder /app/[[.ProjectName]] .

EXPOSE 8080
CMD ["./[[.ProjectName]]"]
